### ISSUE TITLE
About Emo-A

### ISSUE THREAD

**Issue by Catherineasdzz** [JingyuanYY/EmoGen#1]
Hello, could you please explain how the metric Emo-A is calculated and obtained? I don't seem to find this part in your code.

**Comment by fengjw0909** [comment]
Thank you for your asking. Our metric Emo-A is implemented in the emo_cls function of file inference.py. We will update Emo-A related code in 'metrics' folder later.

**Comment by Catherineasdzz** [comment]
oh I find it. Thank you for your reply.
