### ISSUE TITLE
It is difficult to generate images that hold content using Emotion Transfer.

### ISSUE THREAD

**Issue by dangsq** [JingyuanYY/EmoGen#12]
I  implemented the training method. After training on the whole dataset, it could generate well emotional images. However, on the Emotion Transfer task, it is difficult to generate the correct semantic content.

Here are some examples:
amusement dress
![image](https://github.com/user-attachments/assets/07e8d912-59ce-446b-9d8d-19b91a6a14cb)
sadness  dress 
![image](https://github.com/user-attachments/assets/d00f3e65-627b-4b45-9d27-067abac17438)
amusement room
![image](https://github.com/user-attachments/assets/46fa7d35-03f6-4381-ba68-e49434b15393)
sadnesss room
![image](https://github.com/user-attachments/assets/e7e38eac-df4f-4a57-b0a5-fa75c0c13927)
disgust room
![image](https://github.com/user-attachments/assets/1448fd5f-bd3d-41d5-8be0-7e2d93c79454)

Whether this is due to randomness. Is there a way to generate images that match the content?

**Comment by dangsq** [comment]
Reasons may be the template "<emotion> sth".  <emotion> seems not be tokenized correctly. If I change the <emotion> to some special word, such as "iti", the problem seem to be ameliorated.

**Comment by fengjw0909** [comment]
The primary focus of our paper is on the task of generating emotional images based on single emotion words. Emotion Transfer serves as an additional experiment; for this experiment, we have fine-tuned numerous parameters. You might consider reducing the number of steps when training the emotion embedding.
