### ISSUE TITLE
How to use the weights to run test without training

### ISSUE THREAD

**Issue by SwethaMagesh** [JingyuanYY/EmoGen#4]
I am trying to use the trained weights and run on some test images. Give me the steps for running inference. 
. Also mapper.pth - what does it denote?

- I cannot train because the organised image folder is not present.

**Comment by hayakae** [comment]
I’d also like to need the mapper.pth with trained weights.
I guess mapper.pth is the weights of a mapping network (such as MLP) to get CLIP features from emotion space.
Though I could run training/main.py and get mapper.pth, the result of the generated image was like the one you mentioned in 3.2 Attribute Loss (p.4). When the emotion category is amusement, most images show amusement parks. 
I think this is because training is not going well, so the mapper.pth with trained weights will be very helpful.
Thanks.

**Comment by ethan-summer** [comment]
> I am trying to use the trained weights and run on some test images. Give me the steps for running inference.我正在尝试使用经过训练的权重并在一些测试图像上运行。给我运行推理的步骤。 . Also mapper.pth - what does it denote?.还有 mapper.pth - 它表示什么？
> 
> * I cannot train because the organised image folder is not present.我无法训练，因为没有组织的图像文件夹。

In the code it's seams like that we need to process the dataset:Emoset to the structure base the attribute, it's really need some time to do,and  the mapper.th also we to train to obtained.

**Comment by ethan-summer** [comment]
> I’d also like to need the mapper.pth with trained weights.我还想需要带有训练有素的权重的 mapper.pth。
> 
> I guess mapper.pth is the weights of a mapping network (such as MLP) to get CLIP features from emotion space.我猜 mapper.pth 是映射网络（例如 MLP）的权重，用于从情感空间获取 CLIP 特征。 Though I could run training/main.py and get mapper.pth, the result of the generated image was like the one you mentioned in 3.2 Attribute Loss (p.4). When the emotion category is amusement, most images show amusement parks. 虽然我可以运行 training/main.py 并获取 mapper.pth，但生成的图像的结果就像您在 3.2 属性损失（第 4 页）中提到的结果一样。当情感类别为娱乐时，大多数图像显示游乐园。
> 
> I think this is because training is not going well, so the mapper.pth with trained weights will be very helpful.我认为这是因为训练进行得不顺利，所以带有训练有素的权重的 mapper.pth 将非常有帮助。 Thanks. 谢谢。

Hi, I think you have successfully processed the original data set and trained to generate mapper.pth. Could you please provide the processing script file?

**Comment by ZHOU1023** [comment]
> > 我还想需要带有训练有素的权重的 mapper.pth。
> > 我猜 mapper.pth 是映射网络（例如 MLP）的权重，用于从情感空间获取 CLIP 特征。虽然我可以运行 training/main.py 并获取 mapper.pth，但生成的图像的结果就像您在 3.2 属性损失（第 4 页）中提到的结果一样。当情感类别为娱乐时，大多数图像显示游乐园。虽然我可以运行 training/main.py 并获取 mapper.pth，但生成的图像的结果就像您在 3.2 属性损失（第 4 页）中提到的结果一样。当情感类别为娱乐时，大多数图像显示游乐园。
> > 我认为这是因为训练进行得不顺利，所以带有训练权重的 mapper.pth 将非常有帮助.我认为这是因为训练进行得不顺利，所以带有训练有素的权重的 mapper.pth 将非常有帮助。谢谢。谢谢。
> 
> 嗨，我认为您已经成功处理了原始数据集并训练生成了 mapper.pth。您能否提供处理脚本文件？

Can you please tell me how to handle the training dataset? Because data_root is not present.

**Comment by ethan-summer** [comment]
> > > 我还想需要带有训练有素的权重的 mapper.pth。
> > > 我猜 mapper.pth 是映射网络（例如 MLP）的权重，用于从情感空间获取 CLIP 特征。虽然我可以运行 training/main.py 并获取 mapper.pth，但生成的图像的结果就像您在 3.2 属性损失（第 4 页）中提到的结果一样。当情感类别为娱乐时，大多数图像显示游乐园。虽然我可以运行 training/main.py 并获取 mapper.pth，但生成的图像的结果就像您在 3.2 属性损失（第 4 页）中提到的结果一样。当情感类别为娱乐时，大多数图像显示游乐园。
> > > 我认为这是因为训练进行得不顺利，所以带有训练权重的 mapper.pth 将非常有帮助.我认为这是因为训练进行得不顺利，所以带有训练有素的权重的 mapper.pth 将非常有帮助。谢谢。谢谢。
> > 
> > 
> > 嗨，我认为您已经成功处理了原始数据集并训练生成了 mapper.pth。您能否提供处理脚本文件？
> 
> Can you please tell me how to handle the training dataset? Because data_root is not present.你能告诉我如何处理训练数据集吗？因为data_root不存在。

you should create the dataset by yourself

**Comment by ZHOU1023** [comment]
> > > > 我还想需要带有训练有素的权重的 mapper.pth。
> > > > 我猜 mapper.pth 是映射网络（例如 MLP）的权重，用于从情感空间获取 CLIP 特征。虽然我可以运行 training/main.py 并获取 mapper.pth，但生成的图像的结果就像您在 3.2 属性损失（第 4 页）中提到的结果一样。当情感类别为娱乐时，大多数图像显示游乐园。虽然我可以运行 training/main.py 并获取 mapper.pth，但生成的图像的结果就像您在 3.2 属性损失（第 4 页）中提到的结果一样。当情感类别为娱乐时，大多数图像显示游乐园。
> > > > 我认为这是因为训练进行得不顺利，所以带有训练权重的 mapper.pth 将非常有帮助.我认为这是因为训练进行得不顺利，所以带有训练有素的权重的 mapper.pth 将非常有帮助。谢谢。谢谢。
> > > 
> > > 
> > > 嗨，我认为您已经成功处理了原始数据集并训练生成了 mapper.pth。您能否提供处理脚本文件？
> > 
> > 
> > Can you please tell me how to handle the training dataset? Because data_root is not present.你能告诉我如何处理训练数据集吗？因为data_root不存在。
> 
> you should create the dataset by yourself

I downloaded the EmoSet dataset, but I don't have the EmoSet/0103_split_to_folder/ path. Do I need to categorize the scene and object myself?

**Comment by fengjw0909** [comment]
> I’d also like to need the mapper.pth with trained weights.
> 
> I guess mapper.pth is the weights of a mapping network (such as MLP) to get CLIP features from emotion space. Though I could run training/main.py and get mapper.pth, the result of the generated image was like the one you mentioned in 3.2 Attribute Loss (p.4). When the emotion category is amusement, most images show amusement parks. 
> 
> I think this is because training is not going well, so the mapper.pth with trained weights will be very helpful. Thanks.

Thank you for reaching out regarding the trained weights. Unfortunately, during the data organization process, an inadvertent loss occurred, and the trained weights are no longer available.

I recommend training a new set of weights based on the available data to achieve the desired results. If you need any assistance or guidance on training the weights, please feel free to let me know, and I will be happy to help in any way I can.

**Comment by fengjw0909** [comment]
> > > > > 我还想需要带有训练有素的权重的 mapper.pth。
> > > > > 我猜 mapper.pth 是映射网络（例如 MLP）的权重，用于从情感空间获取 CLIP 特征。虽然我可以运行 training/main.py 并获取 mapper.pth，但生成的图像的结果就像您在 3.2 属性损失（第 4 页）中提到的结果一样。当情感类别为娱乐时，大多数图像显示游乐园。虽然我可以运行 training/main.py 并获取 mapper.pth，但生成的图像的结果就像您在 3.2 属性损失（第 4 页）中提到的结果一样。当情感类别为娱乐时，大多数图像显示游乐园。
> > > > > 我认为这是因为训练进行得不顺利，所以带有训练权重的 mapper.pth 将非常有帮助.我认为这是因为训练进行得不顺利，所以带有训练有素的权重的 mapper.pth 将非常有帮助。谢谢。谢谢。
> > > > 
> > > > 
> > > > 嗨，我认为您已经成功处理了原始数据集并训练生成了 mapper.pth。您能否提供处理脚本文件？
> > > 
> > > 
> > > Can you please tell me how to handle the training dataset? Because data_root is not present.你能告诉我如何处理训练数据集吗？因为data_root不存在。
> > 
> > 
> > you should create the dataset by yourself
> 
> I downloaded the EmoSet dataset, but I don't have the EmoSet/0103_split_to_folder/ path. Do I need to categorize the scene and object myself?

Thank you for your inquiry. Indeed, you will need to construct the dataset on your own. While this step may be somewhat tedious, the process itself is relatively straightforward.

Alternatively, you may choose to wait until we have completed the optimization of EmoSet labels. Once this task is finalized, we will release the new labeled folders for your convenience.

**Comment by hayakae** [comment]
This is what I made to create the dataset :)
`import json
import os
import shutil

#EmoSet118Kを"object","scene"に分類

root_annotation = '/home/user/code/EmoGen/EmoSet-118K/annotation'
root_image = '/home/user/code/EmoGen/EmoSet-118K/image'
root_new = '/home/user/code/EmoGen/arranged_EmoSet-118K'


for curDir,_, files in os.walk(root_annotation):
    for file in files:
        if file.endswith("json"):
            #load json file
            json_file_path = os.path.join(curDir,file)
            with open(json_file_path, 'r') as f:
                data = json.load(f)
            
            image_value = data["image_id"]
            emotion_value = data["emotion"]

            if "object" in data:
                object_values = data.get("object",[])
                for object_value in object_values:
                    #make object dir
                    object_dir = os.path.join(root_new, "object", object_value)
                    os.makedirs(object_dir, exist_ok=True)

                    #copy image to object dir
                    image_dir = os.path.join(root_image, emotion_value, image_value + ".jpg")
                    shutil.copy(image_dir, object_dir)

            if "scene" in data:
                #make scene dir
                scene_value = data["scene"]
                scene_dir = os.path.join(root_new, "scene", scene_value)
                os.makedirs(scene_dir,exist_ok=True)

                #copy image to scene dir
                image_dir = os.path.join(root_image, emotion_value, image_value + ".jpg")
                shutil.copy(image_dir, scene_dir)
`

**Comment by konstantinos-giannakakis** [comment]
`import json
import os
import shutil
from tqdm import tqdm

# EmoSet118Kを"object","scene"に分類

root_annotation = "EmoSet-118K/annotation"
root_image = "EmoSet-118K/image"
root_new = "EmoSet-118K_organized"


# Collect all annotation files first for progress bar
annotation_files = []
for curDir, _, files in os.walk(root_annotation):
    for file in files:
        if file.endswith("json"):
            annotation_files.append((curDir, file))

for curDir, file in tqdm(annotation_files, desc="Processing annotations"):
    # load json file
    json_file_path = os.path.join(curDir, file)
    with open(json_file_path, "r") as f:
        data = json.load(f)

    image_value = data["image_id"]
    emotion_value = data["emotion"]

    if "object" in data:
        object_values = data.get("object", [])
        for object_value in object_values:
            # make object dir
            object_dir = os.path.join(root_new, "object", object_value)
            os.makedirs(object_dir, exist_ok=True)

            # create symlink to image in object dir
            image_dir = os.path.join(root_image, emotion_value, image_value + ".jpg")
            symlink_path = os.path.join(object_dir, os.path.basename(image_dir))
            try:
                os.symlink(image_dir, symlink_path)
            except FileExistsError:
                pass

    if "scene" in data:
        # make scene dir
        scene_value = data["scene"]
        scene_dir = os.path.join(root_new, "scene", scene_value)
        os.makedirs(scene_dir, exist_ok=True)

        # create symlink to image in scene dir
        image_dir = os.path.join(root_image, emotion_value, image_value + ".jpg")
        symlink_path = os.path.join(scene_dir, os.path.basename(image_dir))
        try:
            os.symlink(image_dir, symlink_path)
        except FileExistsError:
            pass
`

I made a small adjustment to the script, to include a progress bar and use symlink. Especially usefull for large datasets like the 3.3M
