### ISSUE TITLE
DataSet 

### ISSUE THREAD

**Issue by hustzyj** [JingyuanYY/EmoGen#8]
Hi，thank you for your work！ I have downloaded the emoset dataset, how do I organize the dataset according to its attributes as mentioned in readme？Where can I find a preprocessing script for this?

**Comment by fengjw0909** [comment]
Sorry, we doesn't get the preprocessing script for this. you will need to construct the dataset on your own. While this step may be somewhat tedious, the process itself is relatively straightforward.

Alternatively, you may choose to wait until we have completed the optimization of EmoSet labels. Once this task is finalized, we will release the new labeled folders for your convenience.
